### ISSUE TITLE
Enabling Temination with CTRL + C

### ISSUE THREAD

**Issue by hashimati** [awegmann/consoleui#17] opened 2020-07-17 22:04 UTC
Hi, 

The end-users cannot terminate the prompt.  It is feasible to add this feature.

Thanks for these excellent efforts.

**Comment by awegmann** [comment] 2020-07-24 11:24
Hi.

You're right. CTRL-C should work. I'll check that, fix it and release a new version.

**Comment by hashimati** [comment] 2020-07-24 16:54
Excellent... I'm looking forward to that.

**Comment by awegmann** [comment] 2020-07-25 12:08
Hi Ahmed.

Can you tell me, on which platform you encountered that problem? I'm working with OSX and just checked - on every input I can stop the program with CTRL-C. Or did I misunderstand you, and you want to use CTRL-C to cancel input, but go on with the application?

**Comment by hashimati** [comment] 2020-07-26 17:12
Hi Andreas,

I'm facing this problem on Windows 10. Your understanding is correct which is the termination of the input.

 I'm using PicoCli+Micronaut as a major framework and ConsoleUi + Jline for interactive mode.

Honestly I didn't check if the problem occors without using picocli and Micronaut.

**Comment by awegmann** [comment] 2020-07-26 18:09
Hi Ahmed.

I figured out, that this is an issue of the jline2 library I use. The version on maven central is build on jline2:2.12. I just tested the same version with 'jline:jline:2.14.6' which fixes the issue. Even on Windows its now possible to use CTRL-C to terminate the application.
So if you don't already depend directly on jline2, add an explicit dependency to version 2.14.6. 

Please tell me, if the issue is fixed with this jline version, then I will close the issue.

The corresponding jline2 issue: https://github.com/jline/jline2/issues/127

And the latest jline2 version: https://search.maven.org/artifact/jline/jline/2.14.6/jar

**Comment by hashimati** [comment] 2020-07-26 19:44
Hi Andreas,


Cool, it's working now.

I had tested on Linux also. The issue doesn't occur with Jline 2.12. 

Thanks a lot...

**Closed as completed** 2020-07-27 19:19 UTC
